version: "3.5"

services:
  nas:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - .:/mnt/test:ro
    ports:
      - 139:139
      - 445:445
      - 137:137
      - 138:138
      - 137:137/udp
      - 138:138/udp
      - 445:445/udp
      - 8080:80
    environment:
     TZ: Europe/Paris
     CONFIG: >
      {
          "groups": [
              {
                  "name": "family",
                  "id": 1100
              }
          ],
          "users": [
              {
                  "name": "me",
                  "id": "1001",
                  "groups": ["family"],
                  "password": "myself"
              },
              {
                  "name": "spouse",
                  "id": "1002",
                  "groups": ["family"],
                  "password": "heshe"
              },
              {
                  "name": "anybody",
                  "id": "1003",
                  "password": null
              }
          ],
          "guestUser": "anybody",
          "shares": [
              {
                  "channels": ["smb", "webdav"],
                  "name": "music",
                  "path": "/mnt/test",
                  "visible": true,
                  "uMasks": {
                    "allowedForFiles": "0660",
                    "allowedForDirs": "0770",
                    "forcedForFiles": "0660",
                    "forcedForDirs": "0770",
                    "recycleDir": "0770"
                  },
                  "recycle": true,
                  "permissions": [
                      {
                          "mode": "rw",
                          "users": ["me"],
                          "groups": ["family"]
                      },
                      {
                          "mode": "ro",
                          "guest": true
                      }
                  ]
              }
          ]
      }
